export enum AuditAction {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGOUT = "LOGOUT",

    REGISTER = "REGISTER",
    EMAIL_VERIFIED = "EMAIL_VERIFIED",

    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",
    PASSWORD_CHANGE = "PASSWORD_CHANGE",

    TOKEN_REFRESH = "TOKEN_REFRESH",

    ROLE_CREATED = "ROLE_CREATED",
    ROLE_UPDATED = "ROLE_UPDATED",
    ROLE_DELETED = "ROLE_DELETED",

    PERMISSION_UPDATED = "PERMISSION_UPDATED",

    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
    ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
}

export enum AuditSeverity {
    INFO = "INFO",
    WARN = "WARN",
    CRITICAL = "CRITICAL"
}